#!/usr/bin/env python3
from pathlib import Path
import re,csv,collections,sys
ROOT=Path(__file__).resolve().parents[1]
feature_files=[]
for d in ROOT.iterdir():
    if d.is_dir() and re.match(r'^\d\d_',d.name) and d.name!='00_governance':
        feature_files += sorted(d.glob('[0-9][0-9]_*.md'))
pat_bold=re.compile(r'^\s*-\s+\*\*([A-Z]{2,5}-[A-Z0-9]+-\d{3})\*\*\s+[—-]\s+',re.M)
pat_tick=re.compile(r'^\s*-\s+`([A-Z]{2,5}-[A-Z0-9]+-\d{3})`\s+',re.M)
defs=[]
for f in feature_files:
    text=f.read_text(encoding='utf-8')
    for p in (pat_bold,pat_tick):
        defs += [(m.group(1),f) for m in p.finditer(text)]
counts=collections.Counter(x for x,_ in defs)
dups=[x for x,n in counts.items() if n>1]
scaffold=[]
for f in feature_files:
    t=f.read_text(encoding='utf-8')
    if re.search(r'Status:\s*SCAFFOLD|\bPLACEHOLDER\b|\bTODO:\b|\[TBD\]',t,re.I): scaffold.append(f)
qrows=list(csv.DictReader((ROOT/'00_governance/OPEN_QUESTIONS_REGISTRY.csv').open(encoding='utf-8')))
trows=list(csv.DictReader((ROOT/'00_governance/OPEN_QUESTIONS_RESOLUTION_TRACKER.csv').open(encoding='utf-8')))
track=collections.Counter(r['resolution_status'] for r in trows)
acps=list((ROOT/'00_governance/acp').glob('ACP-*.md'))
res=(ROOT/'00_governance/ARCHITECTURE_RESOLUTION_PASS1.md').read_text(encoding='utf-8')
ars=sorted(set(re.findall(r'###\s+(AR-\d{3})\b',res)))
eng=list((ROOT/'engineering').glob('*.md')) if (ROOT/'engineering').exists() else []
errors=[]
if len(feature_files)!=181: errors.append(f'feature count={len(feature_files)} expected=181')
if len(defs)!=2334: errors.append(f'requirement defs={len(defs)} expected=2334')
if dups: errors.append(f'duplicate requirement definitions={len(dups)}')
if scaffold: errors.append(f'scaffold markers={len(scaffold)}')
if len(qrows)!=203: errors.append(f'open questions={len(qrows)} expected=203')
if len(trows)!=203: errors.append(f'tracker rows={len(trows)} expected=203')
if sum(track.values())!=203: errors.append('tracker status total mismatch')
report=ROOT/'00_governance/DOCUMENTATION_INTEGRITY_REPORT.md'
lines=['# Artist OS — Documentation Integrity Report','', '**Generated by:** `tools/check_integrity.py`','',
       f'**Result:** {"PASS" if not errors else "FAIL"}','',
       '## Checks','', '| Check | Result |','|---|---:|',
       f'| Detailed feature specs | {len(feature_files)} |',
       f'| Stable product requirement definitions | {len(defs)} |',
       f'| Unique requirement IDs | {len(counts)} |',
       f'| Duplicate requirement definitions | {len(dups)} |',
       f'| Unfilled scaffold markers | {len(scaffold)} |',
       f'| Extracted open questions | {len(qrows)} |',
       f'| Resolution tracker rows | {len(trows)} |',
       f'| ACP documents | {len(acps)} |',
       f'| Architecture Resolution contracts | {len(ars)} |',
       f'| Engineering-spec markdown files | {len(eng)} |','',
       '## Resolution routing','', '| Status | Count |','|---|---:|']
for k,v in sorted(track.items()): lines.append(f'| {k} | {v} |')
if errors:
    lines += ['', '## Errors'] + [f'- {e}' for e in errors]
else:
    lines += ['', 'No blocking documentation-integrity issues detected by this checker. Semantic approval of ACPs/ARs is still a human architecture review step.']
report.write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(report)
print('PASS' if not errors else 'FAIL', errors)
sys.exit(1 if errors else 0)
